AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - lib/forall/shrink.rb

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceAroundOperators:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Style/AndOr:
  # No setting to prefer 'and' and 'or' to '&&' and '||'
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/MultilineTernaryOperator:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
